spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

security:
  oauth2:
    client:
      id: ${SECURITY_OAUTH2_CLIENT_ID}
      secret: ${SECURITY_OAUTH2_CLIENT_SECRET}
    redirectUri: ${SECURITY_OAUTH2_REDIRECT_URI}