server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  profiles:
    active: dev

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

security:
  oauth2:
    client:
      id: ${SECURITY_OAUTH2_CLIENT_ID}
      secret: ${SECURITY_OAUTH2_CLIENT_SECRET}
    redirectUri: ${SECURITY_OAUTH2_REDIRECT_URI}